### ISSUE TITLE
Sort by size

### ISSUE THREAD

**Issue by Ambrevar** [calancha/dired-du#2]
Is it possible to the dired entries by size?
Using the `-S` flag in `dired-sort-toggle-or-edit` does not work because it uses the results of `ls`, not `du`.

**Comment by Ambrevar** [comment]
@calancha Any idea?

**Comment by Ambrevar** [comment]
Since I don't see a way around dired, I'll go ahead and implement my own `ncdu`-like Emacs package.  I'm thinking of using something like tabulated list.

**Comment by Ambrevar** [comment]
Done: https://gitlab.com/ambrevar/emacs-disk-usage

**Comment by calancha** [comment]
As you mentioned in a previous commit, the library relies upon the external binary **ls** to do the sorting, which is not aware of the sizes returned by **du**.
If the user is not using an external **ls**, then the sorting is made with elisp, so we get control on it.
I have added support for sorting by space in the case the user is using **ls-lisp** without external **ls**, i.e., with **ls-lisp-use-insert-directory-program** set nil.

**Comment by Ambrevar** [comment]
That's great, thanks!
